### PR TITLE
Add global rss filtering

### PR DESCRIPTION
**Pull request by Alioun**
Add global rss filtering as proposed in #19.

### CODE REVIEW

**Comment by schemen** [comment]
Beautiful, thank you! I'll have a look once I wake up properly. I am changing the destination to the dev branch.

**Comment by Alioun** [comment]
Yeah sure!
I'm also having a look into using calibre for the MOBI conversion instead of kcc to circumvent the kindlegen dependency to be able to use it on non x86 machines!

**Comment by schemen** [comment]
Regarding your second point, could you create an issue first so we can properly track it and discuss it :) ?

I am not entirely sure if we can entirely get rid of kindlegen as it allows you to have the manga/comic specific properties added to the emanga.

**Comment by schemen** [comment]
Tested it. With a new database it works as expected, very nice!
I will see to create a database migration path. I will have a look at this today so let's hold this until I have a way to migrate existing databases as this is a change in the db.

**Pull request merged**
